=head1 NAME

jpylyzer - JP2 (JPEG 2000 Part 1) image validator and properties extractor.

=head1 SYNOPSIS

jpylyzer [I<options>] [I<jp2In>]

=head1 DESCRIPTION

JP2 (JPEG 2000 Part 1) image validator and properties extractor
    (C) National Library of the Netherlands / Open Preservation Foundation

=head1 OPTIONS

=over 8

=item B<-h, --help>

Show this help message and exit

=item B<--format FMT, -f FMT>

Validation format; allowed values: jp2, jph, j2c, jhc (default: jp2)

=item B<--mix {1,2}>

Report additional output in NISO MIX format (version 1.0 or 2.0)

=item B<--nopretty>

Suppress pretty-printing of XML output

=item B<--nullxml>

Extract null-terminated XML content from XML and UUID boxes(doesn't affect validation)

=item B<--recurse, -r>

When analysing a directory, recurse into subdirectories (implies --wrapper)

=item B<--packetmarkers, -p>

Report packet-level codestream markers (plm, ppm, plt, ppt)

=item B<--verbose>

Report test results in verbose format

=item B<-v, --version>

Show program's version number and exit

=back

=head1 ARGUMENTS

=over 8

=item B<jp2In>

Input JP2 image(s), may be one or more (whitespace-separated) path expressions; 
prefix wildcard (*) with backslash.

=back

=head1 BUGS

Please report bugs at https://github.com/openpreserve/jpylyzer/issues.

=head1 AUTHORS

B<jpylyzer> was written by Johan van der Knijff <Johan.vanderKnijff@kb.nl> and others.

This manual page was written by Rui Castro <rcastro@keep.pt>.

=head1 COPYRIGHT

This program is free software; you can redistribute it and/or modify it
under the terms of the GNU Lesser General Public License as published by the
Free Software Foundation; either version 3, or (at your option) any
later version.

On Debian GNU/Linux systems, the complete text of the GNU Lesser General
Public License can be found in '/usr/share/common-licenses/LGPL-3'.

=cut
